---
- name: sftponly user 
  hosts: all
  vars_files:
    - "group_vars/{{ ansible_os_family }}.yml"
  remote_user: root
  roles:
    - sftponly
  # sudo: yes

#- name: Install sftponly user
#  hosts: all
#  remote_user: root
  # sudo: yes
#  roles:
    - sftponly
