---

- name: Check if sshd_config was modified
  command: egrep -i ^Subsystem[[:space:]]*sftp[[:space:]]*internal-sftp /etc/ssh/sshd_config
  ignore_errors: True
  register: check_sftp

- name: Configure sshd_config
  include: sftpgroup.yml
  when: check_sftp|failed

- name: Add sftponly group
  group: name={{ sftp_group }} state=present

- name: Check if home users exists
  stat: path="/home/"{{ sftp_user }}
  register: home_check

- name: Change home ownership
  command: "{{ item }}"
  with_items:
    - mkdir -p /home/{{ sftp_user }}
    - chown root.root /home/{{ sftp_user }}
    - chmod 755 /home/{{ sftp_user }}
  when: home_check.stat.exists == false
  
- name: Create sftp user
  user: 
    name: "{{ item.0 }}" 
    createhome: no 
    home: "{{ item.1 }}"
    append: yes 
    shell: /bin/false 
    groups: "{{ sftp_group }}" 
    state: present
    password: "{{ lookup('password', 'credentials/' + inventory_hostname + '/' + sftp_user + '/password.txt encrypt=md5_crypt length=14') }}"
  with_together: 
    - "{{ sftp_user }}"
    - "/home/{{ sftp_user }}"

- name: Add sftp bind mount folder
  file: path=/home/{{ sftp_user }}/{{ bind_mount }} state=directory mode=0775 owner={{ sftp_user }}

- name: Bind mount the folder
  mount:
    src={{ real_mount }}
    name=/home/{{ sftp_user }}/{{ bind_mount }}
    state=mounted
    fstype=none
    opts=bind